"""init

Revision ID: 05f2f8dca7d1
Revises: 
Create Date: 2025-09-05 23:35:38.563948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '05f2f8dca7d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('lift')
    op.drop_table('athlete_flight')
    op.drop_table('exercise')
    op.drop_table('workout')
    op.drop_table('attempt')
    op.drop_table('event')
    op.drop_table('flight')
    op.drop_table('timer')
    op.drop_table('workout_exercise')
    op.drop_table('referee')
    op.drop_table('user')
    op.drop_table('athlete')
    op.drop_table('competition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('sport_type', sa.VARCHAR(length=21), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('config', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('athlete',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('competition_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('bodyweight', sa.FLOAT(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('team', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('current_attempt_number', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('referee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('competition_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('lift_id', sa.INTEGER(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=False),
    sa.Column('remaining_seconds', sa.INTEGER(), nullable=False),
    sa.Column('is_running', sa.BOOLEAN(), nullable=True),
    sa.Column('is_break', sa.BOOLEAN(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('paused_at', sa.DATETIME(), nullable=True),
    sa.Column('current_attempt_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['current_attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['lift_id'], ['lift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('competition_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('weight_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('scoring_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('current_lift_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['current_lift_id'], ['lift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('athlete_id', sa.INTEGER(), nullable=False),
    sa.Column('lift_id', sa.INTEGER(), nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), nullable=False),
    sa.Column('requested_weight', sa.FLOAT(), nullable=False),
    sa.Column('actual_weight', sa.FLOAT(), nullable=True),
    sa.Column('result', sa.VARCHAR(length=12), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('referee_decisions', sqlite.JSON(), nullable=True),
    sa.Column('lifting_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['lift_id'], ['lift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('muscle_group', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('athlete_flight',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('athlete_id', sa.INTEGER(), nullable=False),
    sa.Column('flight_id', sa.INTEGER(), nullable=False),
    sa.Column('lot_number', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lift',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), nullable=True),
    sa.Column('attempt_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('break_time_seconds', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('athlete_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('lift_id', sa.INTEGER(), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), nullable=True),
    sa.Column('calculated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['lift_id'], ['lift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
