from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import CircularDependencyError, OperationalError
"""Update version 2

Revision ID: 0a700744d681
Revises: a095058ddf61
Create Date: 2025-09-19 20:37:02.476018

"""


# revision identifiers, used by Alembic.
revision = '0a700744d681'
down_revision = 'a095058ddf61'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)

    try:
        with op.batch_alter_table('attempt', schema=None) as batch_op:
            # ...existing code...
            # batch_op.alter_column('started_at', existing_type=sa.DateTime(), nullable=False)
            # batch_op.drop_column('some_old_col')
            # batch_op.add_column(sa.Column('new_col', sa.Integer(), nullable=True))
            ...
    except CircularDependencyError:
        existing_cols = inspector.get_columns('attempt') if 'attempt' in inspector.get_table_names() else []
        existing_names = {c['name'] for c in existing_cols}

        try:
            if 'new_col' not in existing_names:
                op.add_column('attempt', sa.Column('new_col', sa.Integer(), nullable=True))

            if 'some_old_col' in existing_names:
                raise RuntimeError(
                    "Migration requires dropping column 'some_old_col' from 'attempt'. "
                    "SQLite cannot drop columns safely here. Edit this migration to manually "
                    "recreate the table without that column, or perform the change manually "
                    "on the DB. See migrations/versions/0a700744d681_update_version_2.py."
                )

        except OperationalError as e:
            raise RuntimeError("Fallback column operations failed: " + str(e))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attempt_athlete_id', type_='foreignkey')
        batch_op.drop_column('athlete_id')

    # ### end Alembic commands ###
