"""Update version 2

Revision ID: 0a700744d681
Revises: a095058ddf61
Create Date: 2025-09-19 20:37:02.476018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a700744d681'
down_revision = 'a095058ddf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('athlete_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_attempt_athlete_id', 'athlete', ['athlete_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attempt_athlete_id', type_='foreignkey')
        batch_op.drop_column('athlete_id')

    # ### end Alembic commands ###
