"""Add violations field to referee decision log

Revision ID: 0b6ea5018ef6
Revises: a122cebf52f1
Create Date: 2025-10-07 10:12:17.718001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6ea5018ef6'
down_revision = 'a122cebf52f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referee_decision_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('violations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referee_decision_log', schema=None) as batch_op:
        batch_op.drop_column('violations')

    # ### end Alembic commands ###
