"""make competition id nuallable

Revision ID: 10c65669bb55
Revises: a095058ddf61
Create Date: 2025-09-19 22:07:09.087599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c65669bb55'
down_revision = 'a095058ddf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.alter_column('competition_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.alter_column('competition_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
