"""Add order column to AthleteFlight table

Revision ID: 31d829114901
Revises: 28c06c9dbf94
Create Date: 2025-09-22 01:18:52.244288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d829114901'
down_revision = '28c06c9dbf94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_flight', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
