"""Add flight_id to attempt table

Revision ID: 31de5170ec22
Revises: 3cc63ec0b47f
Create Date: 2025-10-02 20:28:15.994337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31de5170ec22'
down_revision = '3cc63ec0b47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_id', sa.Integer(), nullable=True))
    
    # Update existing attempts to link them to flights based on athlete_flight relationship
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE attempt 
        SET flight_id = (
            SELECT af.flight_id 
            FROM athlete_flight af 
            WHERE af.athlete_id = attempt.athlete_id 
            LIMIT 1
        )
        WHERE flight_id IS NULL
    """))
    
    # Now make the column non-nullable and add foreign key
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.alter_column('flight_id', nullable=False)
        batch_op.create_foreign_key('fk_attempt_flight_id', 'flight', ['flight_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attempt_flight_id', type_='foreignkey')
        batch_op.drop_column('flight_id')

    # ### end Alembic commands ###
