"""Add status column to attempt table

Revision ID: 3cc63ec0b47f
Revises: 97e187ef92b3
Create Date: 2025-10-02 20:02:20.896084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc63ec0b47f'
down_revision = '97e187ef92b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
