"""make flight event nullable


Revision ID: 514d3cf55ebd
Revises: 10c65669bb55
Create Date: 2025-09-19 22:19:39.210752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514d3cf55ebd'
down_revision = '10c65669bb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
