"""first version all database models, initilization

Revision ID: 70a265a4a7d7
Revises: 
Create Date: 2025-09-15 13:35:57.991198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a265a4a7d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
