"""Add movement type constraints and update athlete entry constraints

Revision ID: 97e187ef92b3
Revises: d1106197ccc4
Create Date: 2025-10-02 18:27:40.642174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e187ef92b3'
down_revision = 'd1106197ccc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_entry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_athlete_event_lift'), type_='unique')
        batch_op.create_unique_constraint('uq_athlete_flight_lift', ['athlete_id', 'flight_id', 'lift_type'])

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_event_movement_flight', ['event_id', 'movement_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_constraint('uq_event_movement_flight', type_='unique')

    with op.batch_alter_table('athlete_entry', schema=None) as batch_op:
        batch_op.drop_constraint('uq_athlete_flight_lift', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_athlete_event_lift'), ['athlete_id', 'event_id', 'lift_type'])

    # ### end Alembic commands ###
