"""Updated db

Revision ID: a095058ddf61
Revises: 
Create Date: 2025-09-19 19:48:42.021903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a095058ddf61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'athlete' in inspector.get_table_names():
        cols = [c['name'] for c in inspector.get_columns('athlete')]
        if 'weight_category' in cols:
            with op.batch_alter_table('athlete', schema=None) as batch_op:
                batch_op.drop_column('weight_category')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_category', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
