"""Add referee decision log table

Revision ID: a122cebf52f1
Revises: 
Create Date: 2025-10-07 08:39:24.342282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a122cebf52f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referee_decision_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=True),
    sa.Column('flight_name', sa.String(length=50), nullable=True),
    sa.Column('athlete_name', sa.String(length=255), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('weight_class', sa.String(length=50), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('current_lift', sa.String(length=100), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempt_weight', sa.Float(), nullable=True),
    sa.Column('decision_label', sa.String(length=100), nullable=False),
    sa.Column('decision_value', sa.Boolean(), nullable=False),
    sa.Column('decision_color', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referee_decision_log')
    # ### end Alembic commands ###
