"""Add competition_id and order columns to Flight and AthleteFlight tables

Revision ID: b6243731a7c5
Revises: 31d829114901
Create Date: 2025-09-22 01:43:21.580414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6243731a7c5'
down_revision = '31d829114901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_flight_competition_id', 'competition', ['competition_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_constraint('fk_flight_competition_id', type_='foreignkey')
        batch_op.drop_column('competition_id')

    # ### end Alembic commands ###
