"""empty message

Revision ID: b7cc1db9f27f
Revises: ca818a0e90fa
Create Date: 2025-09-23 01:59:12.633945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cc1db9f27f'
down_revision = 'ca818a0e90fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_entry', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_athlete_entry_event', 'event', ['event_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
