"""Add event and lift information to AthleteEntry

Revision ID: ca818a0e90fa
Revises: 
Create Date: 2025-09-23 00:25:23.085717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca818a0e90fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lift_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('attempt_time_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('break_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('entry_config', sa.JSON(), nullable=True))
    batch_op.create_foreign_key('fk_athlete_entry_event_id', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_entry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_athlete_entry_event_id', type_='foreignkey')
        batch_op.drop_column('entry_config')
        batch_op.drop_column('break_time')
        batch_op.drop_column('attempt_time_limit')
        batch_op.drop_column('lift_type')
        batch_op.drop_column('category')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
