"""add opening_weights column to athlete_entry

Revision ID: d3cb1f64182a
Revises: b6243731a7c5
Create Date: 2025-09-22 17:09:06.908514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cb1f64182a'
down_revision = 'b6243731a7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_weights', sa.JSON(), nullable=True))

    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('athlete_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_attempt_athlete_id', 'athlete', ['athlete_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attempt_athlete_id', type_='foreignkey')
        batch_op.drop_column('athlete_id')

    with op.batch_alter_table('athlete_entry', schema=None) as batch_op:
        batch_op.drop_column('opening_weights')

    # ### end Alembic commands ###
