"""Removed scoring type from event table

Revision ID: d4accc2e4d8e
Revises: b6243731a7c5
Create Date: 2025-09-22 18:51:07.296357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4accc2e4d8e'
down_revision = 'b6243731a7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('scoring_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoring_type', sa.VARCHAR(length=4), nullable=False))

    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
