"""Add age field to Athlete model

Revision ID: d7ffa5ecd5a5
Revises: 4d21b345e621
Create Date: 2025-09-19 12:31:29.200340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ffa5ecd5a5'
down_revision = '4d21b345e621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
