name: CI

on:
  pull_request:
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          flake8 .
      - name: Tests
        env:
          FLASK_ENV: testing
          SECRET_KEY: test-secret
          SQLALCHEMY_DATABASE_URI: sqlite://
        run: |
          pytest -q
